[package]
name = "saphyr-serde"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
saphyr-parser = "0.0.4"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"

[dev-dependencies]
serde_json = "1.0.140"
